---
##########
# DOCKER #
##########

mgr_containerized_deployment: false
mgr_containerized_deployment_with_kv: false
ceph_docker_image: "ceph/daemon"
ceph_docker_image_tag: latest
ceph_mgr_docker_extra_env: -e CLUSTER={{ cluster }} -e MGR_NAME={{ ansible_hostname }}
ceph_docker_on_openstack: false
ceph_config_keys: [] # DON'T TOUCH ME
